spring:
  application:
    name: payment-gateway-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

flip:
  token: "Basic SkRKNUpERXpKREZ0T0dSQk9HZENaMkZOT0ZwdGFFeHlNbEJYVFdWVWJtNHpSRGRNYmt4T1dVUXZNR1pLZG1KSlNqWjZSbkozU2xWU2MzVkw="
  bank-inquiry-url: "https://bigflip.id/big_sandbox_api/v2/disbursement/bank-account-inquiry"
  callback-validasi-token: "$2y$13$qxPxoKY9yrkq5qLSmsijtuUEWxKuE7nZI/uJntyGzXi2FN/i2SL.O"
  disbursment-url: "https://bigflip.id/big_sandbox_api/v3/disbursement"
  api-key-bill-payment-url: "https://bigflip.id/big_sandbox_api/v2/pwf/bill"
  api-key-get-bill-payment-link: "https://bigflip.id/big_sandbox_api/v2/pwf/{linkId}/bill"
